// shared/codegen/gen-types.mjs
// 极简 JSON-schema → TS 生成器，覆盖本项目用到的子集
// （object/integer/string/boolean/array/enum/null/oneOf/$ref）。
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const schemaPath = join(here, '..', 'api-schema.json');
const outPath = join(here, '..', 'generated', 'types.ts');
const schema = JSON.parse(readFileSync(schemaPath, 'utf8'));

function tsType(node) {
  if (node.$ref) return node.$ref.replace('#/definitions/', '');
  if (node.enum) return node.enum.map((v) => JSON.stringify(v)).join(' | ');
  switch (node.type) {
    case 'integer': return 'number';
    case 'number': return 'number';
    case 'boolean': return 'boolean';
    case 'string': return 'string';
    case 'null': return 'null';
    case 'array': return `Array<${tsType(node.items)}>`;
    case 'object': return inlineObject(node);
    case undefined:
      if (node.oneOf) return `(${node.oneOf.map(tsType).join(' | ')})`;
      return 'unknown';
    default: return 'unknown';
  }
}
function inlineObject(node) {
  const props = node.properties ?? {};
  const required = new Set(node.required ?? []);
  const fields = Object.entries(props).map(([name, sub]) => {
    const opt = required.has(name) ? '' : '?';
    return `  ${name}${opt}: ${tsType(sub)};`;
  });
  return `{\n${fields.join('\n')}\n}`;
}

const defs = schema.definitions ?? {};
const blocks = Object.entries(defs).map(([name, node]) => {
  const t = tsType(node);
  return t.startsWith('{') ? `export interface ${name} ${t}` : `export type ${name} = ${t};`;
});

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath,
  `// AUTO-GENERATED by shared/codegen/gen-types.mjs — do not edit.\n` +
  `// Source: shared/api-schema.json\n\n` +
  blocks.join('\n\n') + '\n');
console.log(`generated ${outPath}`);
